projects:
  - name: 0xda-market
    environments:
      - name: Test
        services:
          - type: web
            name: 0xda-market-test
            runtime: docker
            plan: free
            region: frankfurt
            branch: master
            dockerfilePath: ./Dockerfile
            dockerContext: .
            healthCheckPath: /health
            autoDeployTrigger: checksPass
            envVars:
              - key: DEPLOY_ENV
                value: development
              - key: PUBLIC_API_TOKEN
                sync: false
              - key: MANUAL_PROVIDER_TOKEN
                sync: false
              - key: DATABASE_URL
                sync: false
      - name: Production
        services:
          - type: web
            name: 0xda-market
            runtime: docker
            plan: free
            region: frankfurt
            branch: release
            dockerfilePath: ./Dockerfile
            dockerContext: .
            healthCheckPath: /health
            autoDeployTrigger: checksPass
            envVars:
              - key: DEPLOY_ENV
                value: production
              - key: PUBLIC_API_TOKEN
                sync: false
              - key: MANUAL_PROVIDER_TOKEN
                sync: false
              - key: DATABASE_URL
                sync: false
